
@echo off
set list=wp_commentmeta wp_comments wp_failed_jobs wp_links wp_mailchimp_carts wp_options wp_postmeta wp_posts wp_queue wp_term_relationships wp_term_taxonomy wp_termmeta wp_terms wp_usermeta wp_users wp_wc_download_log wp_wc_product_meta_lookup wp_wc_webhooks wp_wcfm_daily_analysis wp_wcfm_detailed_analysis wp_wcfm_enquiries wp_wcfm_enquiries_meta wp_wcfm_enquiries_response wp_wcfm_following_followers wp_wcfm_marketplace_orders wp_wcfm_marketplace_orders_meta wp_wcfm_marketplace_product_multivendor wp_wcfm_marketplace_refund_request wp_wcfm_marketplace_reverse_withdrawal wp_wcfm_marketplace_review_rating_meta wp_wcfm_marketplace_reviews wp_wcfm_marketplace_reviews_response wp_wcfm_marketplace_shipping_zone_locations wp_wcfm_marketplace_shipping_zone_methods wp_wcfm_marketplace_store_taxonomies wp_wcfm_marketplace_vendor_ledger wp_wcfm_marketplace_withdraw_request wp_wcfm_marketplace_withdraw_request_meta wp_wcfm_membership_subscription wp_wcfm_messages wp_wcfm_messages_modifier wp_wcfm_messages_stat wp_wcfm_support wp_wcfm_support_meta wp_wcfm_support_response wp_woocommerce_api_keys wp_woocommerce_attribute_taxonomies wp_woocommerce_downloadable_product_permissions wp_woocommerce_log wp_woocommerce_order_itemmeta wp_woocommerce_order_items wp_woocommerce_payment_tokenmeta wp_woocommerce_payment_tokens wp_woocommerce_sessions wp_woocommerce_shipping_zone_locations wp_woocommerce_shipping_zone_methods wp_woocommerce_shipping_zones wp_woocommerce_tax_rate_locations wp_woocommerce_tax_rates wp_wp_api_social

(for %%a in (%list%) do (
 echo %%a

 mysqldiff --server1=root:P@ssword@localhost:3306 --server2=root:P@ssword@localhost:3306 --changes-for=server1 --show-reverse --difftype=sql wine2db.%%a:wine2wp.%%a > %%a.sql

))
